### PR TITLE
fix: update spring-security

### LINKED ISSUE #79: Utbedring av spring-security i dataservice-catalog
- [x] Alle feil ifbm token svarer nå med 500, burde svare med enten 401 eller 403
- [x] Legg til audience-sjekk
- [x] Oppdater spring-boot og spring-security

### PR DESCRIPTION
**Pull request by NilsOveTen**
resolves #79

### CODE REVIEW

**Review by frederik-ronnevig — APPROVED** [review]

File: src/main/java/no/fdk/dataservicecatalog/security/SystemRootAdminRole.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    static final String resourceRole = "admin";
+
+    public String getResourceType() {
+        return systemType;
+    }
+    public String getResourceId() {
+        return rootId;
+    }
+
+    public Boolean matchPermission(String type, String id, String permission) {
```
Comment (jeffreiffers) [inline src/main/java/no/fdk/dataservicecatalog/security/SystemRootAdminRole.java:23]:
```suggestion
    @Override
    public Boolean matchPermission(String type, String id, String permission) {
```

**Review by jeffreiffers — APPROVED** [review]

**Review by matsjs — APPROVED** [review]
